# Site settings
title: Jan Moros
name: Jan Moros

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/janMoros
 - title: LinkedIn
   url: https://www.linkedin.com/in/jan-moros-201970194

#Any buzzword skills you want to include
skills:
 - Python
 - C++
 - Matlab
 - C#
 - Computer Vision
 - Machine Learning
 - Data Science
 - Artificial Intelligence
 - Videogame Development
 - Web Development
 - SQL
 
# skillsES:
# - Python
# - C++
# - Matlab
# - C#
# - Computer Vision
# - Machine Learning
# - Data Science
# - Inteligencia Artificial
# - Desarrollo de videojuegos
# - Desarrollo Web
# - SQL


#Work experience is required
roles:
 - title: Data Science Intern
   start: Oct 2020
   end: Ongoing
   employer: Delectatech
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
# - title: Senior Engineer
#   start: 2016
#   end: 2017
#   employer: Emerald Street Ventures
#   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
# - title: Senior Engineer
#   start: 2012
#   end: 2016
#   employer: Covestor
#   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
# - title: Associate Manager
#   start: 2005
#   end: 2012
#   employer: Accenture
#   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor's Degree
   GradDate: "Expected graduation: June 2021"
   subject: Computer Engineering
   Specialization: Computational Science
   school: Universitat Autònoma de Barcelona
   CourseWork: "Relevant coursework: Computer Vision, Machine Learning, Analysis and Design of Algorithms, Knowledge, Reasoning and Uncertainty"
   
#educationES:
# - level: Grado
#   GradDate: "Fecha prevista de graduación: junio 2021"
#   subject: Ingeniería Informática
#   Specialization: Computación
#   school: Universitat Autònoma de Barcelona
#   CourseWork: "Relevant coursework: Computer Vision, Machine Learning, Analysis and Design of Algorithms, Knowledge, Reasoning and Uncertainty"

#List of interesting Github repo/projects to include - optional
github:
 - janMoros/Tamed-Souls
 - janMoros/C.A.R.L.E.S
 - janMoros/saferunner
 - janMoros/MNIST_Digits_Classifier
 - janMoros/CrosswordSolver
 - janMoros/3DMazeVGI


#introErasmus: |
#  I am a 3rd grade Computer Engineering student, specialized in <b>Computational Science</b>. Here I have worked with a broad range of languages and technologies, but I have the most experience with <b>C++</b> and <b>Python</b>. This year I have specialized, so I have coursed subjects on <b>Machine Learning</b>, Algorithmic and <b>Computer Vision</b>. I have found this last one to be really interesting. That is the reason I chose to make my international exchange at NHL Stenden, because of the Computer Vision and Data Science course offered there.

intro:
 I am a 4th grade Computer Engineering student, specialized in <b>Computational Science</b>. Here I have worked with a broad range of languages and technologies, but I have the most experience with <b>C++</b> and <b>Python</b>. 
 <br><br>
 This academic year I have coursed a 4-month <b>Data Science internship</b> at <b><a href = "http://www.delectatech.com">Delectatech</a></b>, and I am currently taking the <i>Computer Vision & Data Science</i> minor/internship at NHL Stenden, as an Erasmus Exchange.

#introES:
# Soy estudiante de 3o de Ingeniería informática, con la mención en Computación. Aquí he trabajado con un amplio abanico de lenguajes y tecnologías, pero con los que tengo más experiencia son <b>C++</b> y <b>Python</b>. Busco realizar mi estada de prácticas en una empresa donde pueda aprender sobre diferentes áreas para expandir mi rango de conocimentos.

# Work Experience HARDCODED HERE, NOT JEKILLIFIED
workastext: |
 <h2 class="job">Data Science Internship - <span class="place"><a href="http://www.delectatech.com">Delectatech</a></span> <span class="year">(Oct 2020 - Jan 2021)</span></h2>
 <p>
  Performed dataset labeling, CNN model fine-tuning and Data Analysis.
 </p>
 
 <h2 class="job">Minor in Computer Vision & Data Science - <span class="place"><a href="https://www.nhlcomputervision.nl">NHL Stenden</a></span> <span class="year">(Feb 2021 - Present)</span></h2>
 <p>
  Internship at the NHL Stenden Centre of Expertise in Computer Vision & Data Science. <br>
  Applied research project focused on Obstacle Detection for a drone's fail-safe landing system.
 </p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <h2>Languages</h2>
   Catalan - Native <br>
   Spanish - Native <br>
   <b>English - CEFT C1</b> <br>
   <br>
   <h2>Sports</h2>
   Fencer at Club d’Esgrima Ciutat de Terrassa - 2013 to 2016 <br>
   American Football player at Terrassa Reds - 2016 to 2018 <br>
   <br>
   <h2>Volunteering</h2>
   Leisure Monitor at Esplai Egara - 2018 to 2020 <br>
   (Esplai is a Catalan word that refers to an association that thrives for educational leisure time) <br>
   <br>
   <h2>Other Education</h2>
   Youth Recreational Leader certificate - Escola Lliure el sol - 2018 <br>
   Proficient at C1 oral fluency diploma - Universidad Internacional Menéndez Pelayo <br>
   <br>
   <h2>Unrelated Work Experience</h2>
   Summer Camp Leisure Monitor - Grup Formació i Oci - Summer 2018 <br>
   Private teacher for children of different ages - 2016 to 2020 <br>
   
#additionalinfoES: |
#   <h2>Idiomas</h2>
#   Catalán - Nativo <br>
#   Español - Nativo <br>
#   <b>Inglés - CEFT C1</b> <br>
#   <br>
#   <h2>Sports</h2>
#   Tirador en Club d’Esgrima Ciutat de Terrassa - 2013 a 2016 <br>
#   Jugador de fútbol americano en Terrassa Reds - 2016 a 2018 <br>
#   <br>
#   <h2>Voluntariado</h2>
#   Monitor de ocio en Esplai Egara - 2018 a presente <br>
#   <br>
#   <h2>Educación no formal</h2>
#   Certificado de monitor de ocio - Escola Lliure el sol - 2018 <br>
#   Diploma de competencia oral de nivel C1 en inglés - Universidad Internacional Menéndez Pelayo <br>
#   <br>
#   <h2>Experiencia laboral no relacionada</h2>
#   Monitor de ocio en Casales de verano - Grup Formació i Oci - Verano de 2018 <br>
#   Profesor particular de estudiantes de diferentes edades - 2016 to 2020 <br>

